---
title: "ESM244_Lab1"
author: "Anne Youngdahl"
date: "2023-01-13"
output: html_document
---

```{r setup, include=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE) 
# this controls options for all subsequent chunks.
# true/false controls what shows up in final document. 

# attach packages
library(tidyverse)
library(here)
library(sf) # clean package for working with spatial data
library(tmap) # for visualizing map data
```

### Read in data

```{r}

#read in data
sf_trees <- read_csv(here('data', 'sf_trees', 'sf_trees.csv'))

# practice with dplyr and tidyverse functions
top_5_status <- sf_trees %>% 
  group_by(legal_status) %>% 
  summarize(tree_count = n()) %>% 
  slice_max(tree_count, n = 5) %>%    #find the max five, slice out
  arrange(-tree_count)




```


### Plot practice
### plot top 5
```{r}
#plot practice
ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count), y = tree_count)) + 
  geom_col() + 
  labs(y = 'Tree Count', x = 'Legal Status') + 
  coord_flip() + 
  theme_minimal()

```

### keep obs where legal status is "permitted site" and caretaker is "MTA"
```{r}
permitted_mta <- sf_trees %>% 
  filter(legal_status == "Permitted Site", caretaker == "MTA")
```

### keep Blackwood acacia trees, keep only legal_status, date, latitude, and longitude
```{r}
blackwood_acacia <- sf_trees %>% 
  filter(str_detect(species, "Blackwood Acacia")) %>% 
  select(legal_status, date, latitude, longitude)
#note: capitalization matters here!
#str_detect is used to detect strings, from the 'stringr' package

### make a plot
ggplot(data = blackwood_acacia, aes(x = longitude, y = latitude)) + 
  geom_point()
```

### use tidyr::separate() to separate one column into multiple and tidyr::unite() to join two columns into one
this is the "separate" function from the tidyr package. 
```{r}
sf_trees_sep <- sf_trees %>% 
  separate(species, into = c('spp_scientific', 'spp_common'), sep = ' :: ')

sf_trees_unite <- sf_trees %>% 
  unite("id_status", tree_id:species, sep = '_NEW_')

# unite("new_column_name", columnsTOjoin:range, sep = 'separating-character')

```

